# Generated by Django 5.0.6 on 2024-05-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_video_url_alter_lesson_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=0, upload_to='courses/', verbose_name='Фотография курса'),
            preserve_default=False,
        ),
    ]
