# Generated by Django 5.0.6 on 2024-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=2500, verbose_name='Цена курса'),
            preserve_default=False,
        ),
    ]
